### ISSUE TITLE
GET RIVAL'S ID で ERROR になりプレイリストが作成されません

### ISSUE THREAD

**Issue by newgame365** [rakkyo150/GetNearRankMod#1]
PP Curve に変更があった 2021/12/09 あたりから GET RIVAL'S ID で ERROR になりプレイリストが作成できない状態が続いてます。

- BeatSaber の Version: 1.18.3
- GetNearRankMod の Version: 2.3.0, 2.4.0
  - 以前は 2.3.0 を使用しており正常に動作した
  - 2021/12/09 あたりから ERROR を吐くようになった
  - 2.4.0 にアップグレードしたが同様の ERROR を吐いている
- GetNearRankMod.json はデフォルトのまま

こちらの Mod には大変お世話になってます。開発ありがとうございます。
お手すきの際に確認していただけると幸いです。

**Comment by rakkyo150** [comment]
不具合報告ありがとうございます。
ご不便をおかけして申し訳ありません。

12/10にScoreSaberのAPIに変更があったので、それが原因だと思います。
同じタイミングで1.19.0のアップデートがあったことや私の個人的な事情のため、1.19.0のコアMODがリリースされてから対応するつもりでした。
ですが、少なくともその旨をどこかに書いておくべきでしたね。
本当に申し訳ないです。

不具合報告までしてくださったので、すぐに修正版をリリースします。
あまり時間はかからないと思いますので、リリースまでお待ちください。

**Comment by rakkyo150** [comment]
修正版をリリースしました。
確認をしていただけると幸いです。

**Comment by newgame365** [comment]
GetNearRankMod 2.4.1 が正常に動作することを確認しました。
迅速なご対応ありがとうございました。お忙しい中お手数おかけしてしまいすみませんでした。

**Comment by rakkyo150** [comment]
確認ありがとうございます。
こちらこそ、不具合報告してくださってありがとうございました。
